//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace OptimizerEngine {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("OptimizerEngine.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .bmp_alpha
        ///.sgd
        ///.iic
        ///.arkprofile
        ///.dds
        ///.pbm
        ///.pnt
        ///.cgp
        ///.IBF
        ///.MTL
        ///.p2c
        ///.xrc
        ///.ecm
        ///.max
        ///.CST
        ///.Civ5Map
        ///.lst
        ///.cg
        ///.bs
        ///.sdp
        ///.vsndevts_c
        ///.MVR
        ///.pcs10
        ///.CivBEMap
        ///.xaml
        ///.pcs
        ///.manifest
        ///.map
        ///.ngLog
        ///.ws
        ///.9
        ///.log
        ///.yaml
        ///.rmdp
        ///.1-45783947
        ///.archive
        ///.arz
        ///.Properties
        ///.cht
        ///.hl1
        ///.brk
        ///.fev
        ///.dx11_syt
        ///.sav
        ///.ggpk
        ///.str
        ///.Game
        ///.min
        ///.program
        ///.store
        ///.wc
        ///.css
        ///.bdc
        ///.fxo
        ///.vmf
        ///.ITA
        ///.html
        ///.BML
        ///.hl2
        ///.int
        ///.kfm
        ///.isu
        ///.veg
        ///.ma
        ///.ESN
        ///.obj
        ///.kor
        ///.jpn
        ///.pdb
        ///.js
        ///.fnt
        ///.FRA
        ///.mdmp
        ///.CHS
        ///.r [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string HighCompressible {
            get {
                return ResourceManager.GetString("HighCompressible", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ---Archives
        ///.cab
        ///.gz
        ///.msi
        ///.rar
        ///---Images
        ///.gif
        ///.svg
        ///.swf
        ///.jpg
        ///.png
        ///---Audio
        ///.wem
        ///.ogg
        ///.wma
        ///.vsnd_c
        ///.mp3
        ///---Video
        ///.webm
        ///.ogv
        ///.m4v
        ///.wmv
        ///.bik
        ///.bk2
        ///---Docs
        ///.pdf
        ///---Textures
        ///.tfc
        ///---Packages
        ///.iwd
        ///.resource
        ///.ff
        ///.sabs
        ///.sabl
        ///.sdfdata
        ///.gro
        ///.mpq
        ///.001
        ///.002
        ///.003
        ///.004
        ///.005
        ///.006
        ///.007
        ///.008
        ///.009
        ///.010
        ///.011
        ///.012
        ///.013
        ///.014
        ///.015
        ///.016
        ///.017
        ///.018
        ///.019
        ///.020
        ///.021
        ///.022
        ///.023
        ///.024
        ///.025
        ///.026
        ///.027
        ///.028
        ///.029
        ///.030
        ///---Unknown
        ///.clg
        ///.fd
        ///.fbz
        ///.uifont
        ///.vfont
        ///.xnb.
        /// </summary>
        internal static string NonCompressible {
            get {
                return ResourceManager.GetString("NonCompressible", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ---Archives
        ///.cab
        ///.7z
        ///.rar
        ///.msi
        ///---Video
        ///.bik
        ///.bk2
        ///.mkv
        ///.vp6
        ///.wmv
        ///.avi
        ///.mov
        ///.m4v
        ///.ogv
        ///.webm
        ///.ivf
        ///---Images
        ///.jpg
        ///.gif
        ///.png
        ///.swf
        ///---Docs
        ///.chm
        ///.doc
        ///.docx
        ///.pdf.
        /// </summary>
        internal static string NonPerfSensitive {
            get {
                return ResourceManager.GetString("NonPerfSensitive", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ---Code
        ///.exe
        ///.dll
        ///.shader
        ///.usf
        ///.bin
        ///---Settings
        ///.ini
        ///.cfg
        ///.inf
        ///.toc
        ///.cache
        ///.variables
        ///.mo
        ///.txt
        ///---Textures
        ///.tfc
        ///---Audio
        ///.wad
        ///---Packages
        ///.mpq
        ///.gro
        ///.ggpk
        ///.vpk
        ///.pk3
        ///.upk
        ///.ff
        ///.xpak
        ///.sabl
        ///.sabs
        ///.arc
        ///.001
        ///.002
        ///.003
        ///.004
        ///.005
        ///.006
        ///.007
        ///.008
        ///.009
        ///.010
        ///.011
        ///.012
        ///.013
        ///.014
        ///.015
        ///.016
        ///.017
        ///.018
        ///.019
        ///.020
        ///.021
        ///.022
        ///.023
        ///.024
        ///.025
        ///.026
        ///.027
        ///.028
        ///.029
        ///.030.
        /// </summary>
        internal static string PerfSensitive {
            get {
                return ResourceManager.GetString("PerfSensitive", resourceCulture);
            }
        }
    }
}
